import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;
alter table storage.objects enable row level security;
grant usage on schema public,auth,storage to authenticated,anon;
grant select,insert,delete on storage.objects to authenticated;`);
await db.exec(readFileSync('supabase/schema.sql','utf8'));
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
await db.query('insert into auth.users values($1),($2)',[a,b]);
const identity=async(id)=>{await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${id}';`)};
const rpc=async(name,params)=>{const placeholders=params.map((_,i)=>'$'+(i+1)).join(',');return (await db.query(`select public.${name}(${placeholders}) as result`,params)).rows[0].result};
const photo='33333333-3333-4333-8333-333333333333',foreign='44444444-4444-4444-8444-444444444444',reference='55555555-5555-4555-8555-555555555555';
const job='66666666-6666-4666-8666-666666666666',reshoot='77777777-7777-4777-8777-777777777777',reshootPhoto='88888888-8888-4888-8888-888888888888';
await identity(a);
await db.query('insert into photo_assets(id,user_id,path,filename,kind) values($1,$2,$3,$4,$5)',[photo,a,a+'/p.jpg','p.jpg','photo']);
await db.query('insert into photo_assets(id,user_id,path,filename,kind) values($1,$2,$3,$4,$5)',[reference,a,a+'/r.jpg','r.jpg','reference']);
await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['photo-coach',a+'/p.jpg']);
await assert.rejects(db.query('insert into photo_assets(user_id,path,filename,kind) values($1,$2,$3,$4)',[b,b+'/bad.jpg','bad.jpg','photo']),/row-level security/);
await identity(b);
assert.equal((await db.query('select * from photo_assets')).rows.length,0);
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await db.query('insert into photo_assets(id,user_id,path,filename,kind) values($1,$2,$3,$4,$5)',[foreign,b,b+'/b.jpg','b.jpg','photo']);
await assert.rejects(rpc('create_analysis',[job,photo,null,'人像','手机','',null,null]),/照片不存在/);
await identity(a);
await assert.rejects(rpc('create_analysis',[job,photo,foreign,'人像','手机','',null,null]),/参考图不存在/);
assert.equal(await rpc('create_analysis',[job,photo,reference,'人像','相机','自然的街头人像',null,null]),job);
assert.equal(await rpc('create_analysis',[job,photo,reference,'人像','相机','自然的街头人像',null,null]),job);
assert.equal((await db.query('select * from records')).rows.length,1);
await assert.rejects(db.query("update records set status='completed' where id=$1",[job]),/permission denied/);
const first=await rpc('claim_job',['test-model']);assert.equal(first.id,job);assert.equal(first.reference.id,reference);assert.equal(first.attempts,1);
assert.equal(await rpc('claim_job',['test-model']),null);
assert.equal(await rpc('complete_job',[job,'00000000-0000-4000-8000-000000000000',JSON.stringify({issues:[]}),3,'model']),false);
// An expired lease cannot finish; another worker reclaims the same job with a new token.
await db.exec('reset role');await db.query("update records set lease_until=now()-interval '1 second' where id=$1",[job]);await identity(a);
assert.equal(await rpc('heartbeat',['test-model',job,first.lease_token]),false);
const second=await rpc('claim_job',['test-model']);assert.notEqual(second.lease_token,first.lease_token);assert.equal(second.attempts,2);
assert.equal(await rpc('complete_job',[job,first.lease_token,JSON.stringify({issues:[]}),3,'model']),false);
const result={summary:'测试',strengths:['主体清楚'],issues:[{title:'背景',tag:'背景',exercise:{title:'三个背景',steps:['拍三个版本','并排比较'],success_criteria:'主体更清楚'}}],uncertainties:[],reference:null,comparison:null};
assert.equal(await rpc('complete_job',[job,second.lease_token,JSON.stringify(result),4,'test-model']),true);
assert.equal(await rpc('complete_job',[job,second.lease_token,JSON.stringify(result),4,'test-model']),false);
const exercise=await rpc('save_exercise',[job,0]);assert.equal(await rpc('save_exercise',[job,0]),exercise);
await assert.rejects(rpc('set_exercise_state',[exercise,'done']),/先提交重拍/);
await rpc('set_feedback',[job,false]);await assert.rejects(rpc('save_exercise',[job,0]),/没有可用的练习/);await rpc('set_feedback',[job,true]);
await db.query('insert into photo_assets(id,user_id,path,filename,kind) values($1,$2,$3,$4,$5)',[reshootPhoto,a,a+'/reshoot.jpg','reshoot.jpg','photo']);
await rpc('create_analysis',[reshoot,reshootPhoto,null,'人像','手机','',job,exercise]);
const pending=await rpc('claim_job',['test-model']);assert.equal(pending.parent.id,job);assert.equal(pending.exercise.id,exercise);
await identity(b);assert.equal(await rpc('delete_record',[job]),false);assert.equal(await rpc('set_feedback',[job,false]),false);assert.equal((await db.query('select * from records')).rows.length,0);
await identity(a);await assert.rejects(rpc('delete_reference',[reference]),/仍关联点评/);
assert.equal(await rpc('delete_record',[job]),true);
assert.equal(await rpc('complete_job',[reshoot,pending.lease_token,JSON.stringify(result),1,'model']),false);
assert.equal((await db.query('select * from records')).rows.length,0);assert.equal((await db.query('select * from exercises')).rows.length,0);
assert.equal((await db.query('select * from garbage_paths')).rows.length,2);
assert.equal((await db.query('select * from photo_assets')).rows.length,1);
assert.equal(await rpc('delete_reference',[reference]),true);assert.equal((await db.query('select * from garbage_paths')).rows.length,3);
await db.exec('reset role;set role anon;set request.jwt.claim.sub=\'\';');await assert.rejects(rpc('claim_job',['test']),/permission denied/);
console.log('PASS: account & storage isolation, duplicate submit/complete, lease expiry/reclaim, feedback, exercise link, cascade deletion, anonymous access');
await db.close();
